### ISSUE TITLE
"random songs" isn't very random at all

### ISSUE THREAD

**Issue by chetmurthy** [LMS-Community/slimserver#510] opened 2021-01-14 21:03 UTC
I don't really know how to debug this issue.  I'm an experienced Perl programmer, and generally speaking a systems jock, so with some pointers I'm sure I can get going on debugging, so anybody who can suggest how to start, I'd appreciate.

I have a lot of songs in my music database.  And I noticed that somehow "random songs" seems to find the same ones over and over.  I mean, in the last hour it's picked the same "Dead Can Dance" song several times, and this isn't the only instance.  It happens a *lot*.  And of course, this means that many other parts of my library (which I can search for and find) so they're there for sure) just never get played.

Not sure how to diagnose.

**Comment by michaelherger** [comment] 2021-01-15 08:01
This has been the topic of discussions before. Even I believe something is wrong there. Alas, as much as I tried, I didn't find the culprit.

Repetition within a mix should not be possible, as at the beginning of a mix LMS would get the full list of IDs, shuffle and store it. Then it's popping IDs off of that list as new tracks are requested. Once the list is empty it'll start over. The list creation can be found in the RandomPlay plugin's `Mixer.pm`:

https://github.com/Logitech/slimserver/blob/c31478a4b816b371f5d3fef1a02267fed38ec548/Slim/Plugin/RandomPlay/Mixer.pm#L76

It uses the Fischer-Yates shuffling, as implemented in https://github.com/Logitech/slimserver/blob/c31478a4b816b371f5d3fef1a02267fed38ec548/Slim/Player/Playlist.pm#L689. Maybe it's worth checking whether that's implemented correctly? 

FWIW: I'm no longer using that feature enough to be bothered, tbh. I'm mostly using the Don't Stop The Music feature with LastMix or Spotty.

**Comment by rgobbel** [comment] 2021-01-25 18:55
This is a one-line fix. At the beginning of `fischer_yates_shuffle`, add this line:
```perl
srand(time());
```

I did this in our server a few days ago, and the difference is dramatic and wonderful. I'll put in a pull request shortly.

**Comment by michaelherger** [comment] 2021-01-25 20:28
Hmm... if you read the [documentation for `stand`](https://perldoc.perl.org/functions/srand), they clearly state that 

> Do *not* call srand() (i.e., without an argument) more than once per process.

We already do in more than one place... In general people seem to suggest NOT to call it explicitly at all, except for when you actually want to have reproducible randomness (but in that case you'd call it with the same seed). So... not sure.

As I mentioned: this has been topic of discussions before. I believe it's hard to say whether there's a dramatic improvement, as you noticed it. Because in my experience, the randomness felt perfectly fine at times, but sometimes not at all. But the there are some people who claim that this was part of randomness, that you could get result you wouldn't consider random enough...

Could you try to change `stand()` in slimserver.pl to use the timestamp as the seed and see whether this does help, too?

**Comment by rgobbel** [comment] 2021-01-26 07:05
The documentation says not to call srand() without an argument. I didn't. I call srand(time()). There is no doubt in my mind about the dramatic improvement, it's pretty obvious. In any case, I didn't do what they say not to do.

**Comment by rgobbel** [comment] 2021-01-27 01:58
After having looked at this issue more closely, I agree that simply adding `srand(time()) `to the shuffle routine is not a great way to deal with this--in fact, I'm not sure why it works, though as I've mentioned, it does dramatically improve the breadth of the sampling from our library. I suspect that the original problem may be due to the fact that `srand` was being called in slimserver.pl before `daemonize`, so that the child process has actually never had a call to `srand` at all. I moved that call to just after the `fork()` inside of `daemonize`, and I'm running with that now. So far it looks like it may have worked--at least we're not seeing the same old stuff, as we had been. I'll withdraw my initial PR, and if this looks good after running for a while, submit a new one (or just go ahead and make the change--I think what's needed is a call to `srand()` after the `fork()` in `daemonize`, as well as the call near the beginning of `init`.

**Comment by michaelherger** [comment] 2021-04-30 23:39
I consider implementing a shuffling algorithm based on this Spotify article: 

https://engineering.atspotify.com/2014/02/28/how-to-shuffle-songs/

Is this mostly a problem with the tracks mix?

**Comment by chetmurthy** [comment] 2021-05-01 00:13
I continue to see this problem with the "Random Mix -> Random songs" mix.

**Comment by michaelherger** [comment] 2021-05-01 05:20
> I continue to see this problem with the "Random Mix -> Random songs" mix.

Well, there's been no change so far... I was asking about where the issue was most obvious.

**Comment by chetmurthy** [comment] 2021-05-01 05:30
Sorry, didn't mean to imply that a fix had been attempted.  I was just .... being succinct *grin*.  Describing how I elicit the problem, and that it continues to be present.

**Comment by terual** [comment] 2021-05-01 12:18
I thought I would test if the random mix is really random.

- I created a small library with ~800 songs
- I changed Slim::Plugin::RandomPlay::Mixer.pm to export the shuffled ids to a file directly after the  Slim::Player::Playlist::fischer_yates_shuffle call
- From the webbrowser I called RandomPlay.mix('track', '0') from the JavaScript console about 17.000 times
- I counted all the trackID occurences in the first 10 lines in those 17.000 files (because the first 10 songs would be very noticable if they were the same in subsequent calls) and plotted them:

![afbeelding](https://user-images.githubusercontent.com/953758/116782167-e5f0c300-aa87-11eb-872d-d3b74dd56b2f.png)

The ID with the least occurrences in those first 10 lines occurred 173 times.
The ID with the most occurrences in those first 10 lines occurred 251 times.

The expected number of occurrences based on the sample would be 208.7 times.

Based on these data I would say that the randomisation works correctly and maybe indeed the issue is what is described in the Spotify article.

**Comment by michaelherger** [comment] 2021-05-01 15:29
I spent time on this rainy day doing some experiments with "balanced" shuffle following the above Spotify article. Please see my findings here: https://forums.slimdevices.com/showthread.php?114355-How-random-is-random&p=1021166&viewfull=1#post1021166

**Comment by michaelherger** [comment] 2021-05-02 05:38
Please give the latest 8.2 nightly a try. Make sure you select the "balanced" shuffle in the Random Play menu. It should be on by default in most cases.

**Comment by terual** [comment] 2021-05-02 11:22
I have redone the randomness test with the new algorithm and with an expected track occurrence of 200 in my sample the standard deviation increased from 14,1 to 16,8 with the balanced algorithm (as expected). So it is indeed a little less random, but it seems that tracks are indeed better distributed in the playlist.

**Comment by bvrulez** [comment] 2021-06-28 17:42
I am currently working on the app Squeezer and I was thinking about implementing some additional random play options there. The app will shortly have the option to put certain folders as shortcuts on the main menu and I would then add an option to random play just this selected folder (for example). 

In my case it would be a goal to play all tracks of a folder once before randomizing again. But as far as I understand, the random option from the server will be reset every time it is pressed. I think it would add to the feeling of randomness, if the server would make sure no song is played twice.

I have an iPod classic and also iPod Shuffle and the randomness of those products is amazing. Never is a song played twice and also the tracks seem to be picked from very different genres, a great experience. 

Sorry to hijack this issue but I just wanted to make clear that proper random play options from the server are still very important. At the moment, to play random titles from a certain genre via the server, you have to reset your settings for this random setup. It is not possible to save several such settings as favorites. 

Having said this I also need some advice if it is possible to get the number of items of a certain folder or all the ids it contains. Because if I want to implement it in the app I need to get all IDs for one folder, shuffle it and then simply play one and pop this ID from the list. At the moment the command to navigate to a folder seems to return all the whole items which is a lot of traffic and therefore we request just 50 at once (I think). I am still investigating how to do it. But getting just an array of IDs would definitely be much more efficient. Sorry for this long text. If it is misplaced here please remove it or tell me where a better way to discuss this would be. Thanks.

**Comment by michaelherger** [comment] 2021-06-29 05:20
> Sorry to hijack this issue

If you're serious about being sorry, then don't do it... Just create a new issue, or head over to the forums to discuss the idea.

I'm glad you're talking about "the feeling of randomness", which actually is anything but random 😁.

**Comment by mherger** [comment] 2021-06-29 05:21
I'm closing this issue, as I believe we now have enough options to make randomness not so random.

**Closed as completed by mherger** 2021-06-29 05:21 UTC

**Comment by nguillaumin** [comment] 2022-10-03 20:13
I'm having a similar issue but with the random album mix. Over the past 4-5 days I had multiple albums repeat, over a collection of ~1200.

Where is "balanced shuffle" setting? I was unable to find it. Will it apply to random album mixes as well?

**Comment by michaelherger** [comment] 2022-10-17 06:02
Settings/Advanced/Performance

**Comment by nguillaumin** [comment] 2022-10-17 16:28
Thanks, not where I was expecting this :wink: In any case it's already in balanced mode. I'll try to collect some actual data and open a new ticket.

**Comment by v12345vtm** [comment] 2025-12-31 12:36
its almost 2026 , and i have to a lot of songs in my music database. And I noticed that somehow "random songs" seems to find the same ones over and over.
