### ISSUE TITLE
Can't get custom-convert.conf transcoding to work

### ISSUE THREAD

**Issue by Moonbase59** [LMS-Community/slimserver#347] opened 2020-05-24 15:37 UTC
I still use Ubuntu Studio 14.04, and LMS:
```
Logitech Media Server Version: 7.9.2 - 1578996832 @ Tue Jan 14 12:15:02 CET 2020
Hostname: studio1
IP-Adresse des Servers: 192.168.170.32
Server-HTTP-Portnummer: 9000
Betriebssystem: Debian - DE - utf8
Plattformarchitektur: x86_64-linux
Perl-Version: 5.18.2 - x86_64-linux-gnu-thread-multi
Audio::Scan: 0.95
IO::Socket::SSL: 2.068
Datenbankversion: DBD::SQLite 1.34_01 (sqlite 3.7.7.1)
Anzahl erkannter Player: 5
```

Need to get Google TTS files to work, which currently doesn’t (LMS sees the need to transcode but finds no candidate for "R", see https://github.com/ralph-irving/squeezelite/issues/94#issuecomment-630738919). Google generates 32kbps, mono, 24000Hz MPEG ADTS files.

I tried playing around with `/etc/squeezeboxserver/custom-convert.conf` but cannot for the life of me make it work. (I use `curl` to get the data from an SSL-secured `https:` server, because neither `ffmpeg` nor `mpg123` are able to read from the remote. Seems they’re still using `gnutls` instead of OpenSSL.)

This (test) commandline works fine (probably much to improve here):
```bash
curl -s https://has1.xxxxxxxxxxxxxxxx.myfritz.net/api/tts_proxy/9db85dfd5ad7ae70214513f5fbdfd9beef22a76f_de_-_google_translate.mp3 | mpg123 -q -s -w - -  | lame --silent -q 0 --resample 48000 - - > test.mp3
```

I put this into `custom-convert.conf` like so:
```
# For Google TTS with Home Assistant, creates odd mono MP3
mp3 mp3 squeezelite *
        # RT:{BITRATE=--abr %B}D:{RESAMPLE=--resample %D}
        [curl] -s $URL$ | [mpg123] -q -s -w - - | [lame] --silent -q 0 --resample 48000 - -

```
It doesn’t work, in Advanced → File Types it also shows an entry for MP3 with `curl/mpg123` only (instead of the expected `curl/mpg123/lame`). The effect is that the UI shows the (correct) URI, looks like playing, counting up seconds (forever) but never plays any sound.

I’ve never messed with `convert.conf` or `custom-convert.conf` before, so please let me know if I just make some stupid mistake. **The goal is to be able to play TTS messages on all my players, ideally not corrupting MP3 files that come from LMS’ local music library.**

**Comment by Moonbase59** [comment] 2020-05-24 16:06
Tried to strip `custom-convert.conf` down, but to no avail (tried with both `$URL$` and `$FILE$`):
```
# For Google TTS with Home Assistant, creates odd mono MP3
mp3 mp3 squeezelite *
        # RT:{BITRATE=--abr %B}D:{RESAMPLE=--resample %D}
        [curl] -s $URL$ | [lame] --silent -q 0 --resample 48000 --mp3input - -
```
Playing the TTS files from their direct `https:` link using other programs, like browsers, VLC, KODI, wget, etc. works fine.

**Comment by michaelherger** [comment] 2020-05-24 18:53
I'd recommend you take this to forums.slimdevices.com. You'll get better help there.

**Comment by mherger** [comment] 2020-05-26 04:08
Dupe of issue #350

**Closed as completed by mherger** 2020-05-26 04:08 UTC
Labels: duplicate

**Comment by Moonbase59** [comment] 2020-05-26 14:34
Really a dupe? Tested with Picotts in the meantime (generates WAV), same problem. Somehow looks to me as if LMS wants to transcode remote low-bitrade (low-quality?) files.
