### ISSUE TITLE
"Rescan" button in Classic Skin does not work

### ISSUE THREAD

**Issue by Apesbrain** [LMS-Community/slimserver#803] opened 2022-07-22 11:03 UTC
Nothing happens when the button highlighted below is clicked.  This affects Material Skin where I first noticed it.
Note that this button _does_ work in the Default skin.

![Clipboard01](https://user-images.githubusercontent.com/26585705/180425687-216a882d-5b2a-440c-9e3c-ce30f1f7cc90.jpg)
_There is a closed bug [#410](https://github.com/Logitech/slimserver/issues/410) that is related to this.  The bug should not have been closed as the problem remains in current LMS 8.3 beta._

**Comment by michaelherger** [comment] 2022-07-25 14:31
It would probably have been easier to ask to re-open the old report... as nothing has changed (I still can't reproduce the issue), and I'll ask you the same questions as I did over there. In particular this one: https://github.com/Logitech/slimserver/issues/410#issuecomment-785633369

**Comment by mherger** [comment] 2022-07-25 14:33
Closing this again in favour of #410.

**Closed as completed by mherger** 2022-07-25 14:33 UTC
