### ISSUE TITLE
Short mp3 Files not playing, preventing Text To Speech

### ISSUE THREAD

**Issue by thebradleysanders** [LMS-Community/slimserver#198] opened 2018-03-13 16:20 UTC
Mp3 files used for Text to Speech will not play, It seems small files wont play.

**Comment by mherger** [comment] 2018-03-13 16:51
Could you please provide a sample file? Are there any error messages, on display or in server.log?

**Comment by thebradleysanders** [comment] 2018-03-13 21:41
It looks like a previous issue exists: https://github.com/Logitech/slimserver/issues/123
It seems to be a linux squeezelite 1.8+ issue.
The fix is here however I do not know how to apply it.
http://forums.slimdevices.com/showthread.php?97046-Announce-Squeezelite-a-small-headless-squeezeplay-emulator-for-linux-(alsa-only)&p=872412&viewfull=1#post872412

**Comment by mherger** [comment] 2018-03-14 07:48
Ah, you didn't mention the player. Thanks for following up.

Closing as duplicate of issue #123.

**Closed as completed by mherger** 2018-03-14 07:48 UTC
Labels: duplicate
