### ISSUE TITLE
Deezer radio is streamed in mp3 instead of flac

### ISSUE THREAD

**Issue by evgley** [LMS-Community/slimserver#761] opened 2022-02-13 08:20 UTC
Hello !
I'm new to LMS and i'm trying to use it as deezer **lossless** streamer.
It works fine for all cases except streaming deezer **radio** where mp3 format is used.

Also I've tried to find the root cause of the issue and been able to workaround this (inside Deezer plugin).
Here is what I have done first:
- Install Logitech Media Server (v8.2.0, 1627922070, Tue Aug  3 11:28:42 WEDT 2021) perl 5.014001 - MSWin32-x86-multi-thread
- Setup deezer plugin with paid deezer subscription
- Stop LMS
- Added $radioUrl inside getNextTrack to debug log
- Edited latestformat to flac in server.prefs  (seems like it does matter since it is used for calculating $radioUrl in _getNextRadioTrack)
- start LMS and play radio

After this the following appeared in the log:
```
Slim::Plugin::Deezer::ProtocolHandler::_getNextRadioTrack (362) Getting next radio track from SqueezeNetwork: https://www.mysqueezebox.com/api/deezer/v1/radio/getNextTrack?stationId=30891&format=flac
Slim::Plugin::Deezer::ProtocolHandler::_gotNextRadioTrack (376) Got next radio track: {
  album_id => 271_544,
  album_name => "Core",
  artist_id => 4435,
  artist_name => "Stone Temple Pilots",
  canSkip => 0,
  cover => "http://api.deezer.com/2.0/album/271544/image?size=xl",
  duration => 310,
  id => 2_794_367,
  title => "Plush",
  url => "http://cdnt-proxy-e.deezer.com/api/1/5f90df5bef761233e3b7ddc423b3cb8490e5485ebac9d9703187e00a91d1a7150625bb49ed725f4fbd99a4c9bc46ba3caa4339b6dd8a91d9d833d385feedcdb2de7c8d104d2242b6d6c7f6b8836cc4ea.mp3?hdnea=exp=1644838559~acl=/api/1/5f90df5bef761233e3b7ddc423b3cb8490e5485ebac9d9703187e00a91d1a7150625bb49ed725f4fbd99a4c9bc46ba3caa4339b6dd8a91d9d833d385feedcdb2de7c8d104d2242b6d6c7f6b8836cc4ea.mp3*~data=user_id=0,application_id=4817038602~hmac=3c7deda41029e7a89f48b7b06de506eca1c6963d0bb7296ee32c0907eaa3b060&",
}
```
The first weird thing: `format=flac` was passed to `getNextTrack` request, but we have mp3 link in response.
Not sure if it is by design or root cause of the issue, but I still needed for workaround so let's go further.
I've found several places in codebase where mp3 was just replaced to flac in url links. So why not to try the same here ?

I see that track url is calculated inside `_gotNextRadioTrack` and is based on `getFormatForURL` which seems weird\hacky too.
So let's trick it a little and use:
```
$url      = 'deezer://' . $track->{id} . '.flac';
```
instead of:
```
$url      = 'deezer://' . $track->{id} . '.' . __PACKAGE__->getFormatForURL($track->{url});
```

**Now everything works as expected. All radios are streamed in lossless quality.**

I'll be more than happy to provide additional info or even fix this, but i need some advice on further directions:
- Is it bug or feature that mp3 url is returned from `getNextTrack` request with `format=flac` argument ? 
- Seems like it would be great to have some configuration option for streaming quality instead of guessing inside `getFormatForURL`. Is it right direction ?

**Comment by michaelherger** [comment] 2022-02-13 09:57
Are you saying that if you play tracks from the Deezer library, you'd get FLAC, but if you played "radio", then you'd get mp3 instead?

The streaming format should not be handled in LMS, as only Deezer's servers know what you're allowed to play. Therefore MySB would talk to Deezer while browsing the library, or preparing playback. The indicator in LMS is mostly for the players who would fail to play FLAC if they were told they'd have to play MP3 (and vice versa, of course).

**Comment by evgley** [comment] 2022-02-13 10:03
> Are you saying that if you play tracks from the Deezer library, you'd get FLAC, but if you played "radio", then you'd get mp3 instead?

Yes, exactly

> The streaming format should not be handled in LMS, as only Deezer's servers know what you're allowed to play. 

Suppose this is true. But why official deezer apps (mobile and desktop) has settings for quality ? 
I agree that server must decide which quality is available, but I think client should also be able to request preferred format

**Comment by michaelherger** [comment] 2022-02-13 16:08
In a mobile app this setting does make sense if you eg. don't want to stream FLAC while on the road, to save bandwidth.

I'll have to double check to see what's going on there. That `latestformat` trick/hack/workaround already was an attempt at playing radio in the correct format.

**Comment by mherger** [comment] 2022-02-20 12:54
In your initial posting you mentioned that you modified `latestformat`. If that was still set to mp3 or some other lossy format, then that would explain why you didn't get lossless. But the question is why it wasn't update to flac, if indeed you have a subscription. The whole description makes me believe that your (Deezer side) profile somehow wasn't up to date yet. `latestformat` should always be set to the format Deezer is sending you back (in "music on demand" mode, not radio). And if Deezer returns MP3, though you're asking for flac, then it's Deezer's decision to do so. Maybe that one track wasn't available as flac? Can you double check?

**Comment by evgley** [comment] 2022-02-20 16:29
Hi Michael.

First of all, one detail about my account. It is definitely paid subscription but I use free trial. The first real charge will be within 2 weeks. But lossless is available for this account in original Deezer app for sure: I monitor network traffic to check this.

I've done one more test within LMS and the steps are below:

1. Clean installation of LMS+Deezer with  debug logs of deezer module.  The only patched thing is $radioURL added to debug log in _getNextRadioTrack
2. Checked there is NO latestformat in server.prefs
3. Play radio from deezer (this is the first playboack of deezer on this installation).  Applications->Deezer->Web Radio->Rock->Rock classics
4. Request seemed broken. This url was "https://www.mysqueezebox.com/api/deezer/v1/radio/getNextTrack?stationId=37765&format=". 
4. LMS played radio in mp3 format and added "latestFormat: mp3" to server.prefs
5. Found the same track using search and played it. It was in flac and latestformat changed to flac also.
6. Played the same radio again. Request looked fine this time (format=flac), but the response\quality\latestformat dropped to mp3
7. Found last track from the radio again and played it explicitly. The format changed to flac so the track is available in lossless quality.

I've attached server.log corresponding to this description
[server.log](https://github.com/Logitech/slimserver/files/8104416/server.log)
.

**Comment by michaelherger** [comment] 2022-02-23 10:03
I'm sorry for the delay. I'm a bit busy with other things right now. Please let me know if you decide to become a paying customer and the issue continues. I tend to believe that it's a none-issue for paying customers, as I haven't seen any reports of this before. But I'll investigate once I can find the time to do so.

**Comment by MichaelSch** [comment] 2022-05-31 10:00
I am experiencing the same issue. My Deezer account is on the premium plan via 12 month coupon - so no trial.

**Comment by michaelherger** [comment] 2022-06-05 20:52
What kind of radios are you playing? Smart Radio? Flow? Something else?

**Comment by MichaelSch** [comment] 2022-06-05 21:24
Flow and genre based radio. For example go to Deezer - Stilrichtungen - Pop - Radio - Hits.

**Comment by MichaelSch** [comment] 2022-06-06 17:48
It seems like my flow and smart radios depend on the format that has been streamed before while the genre radios (see post above) are always mp3. So starting the flow or a smart radio after playing a genre station is mp3 while it‘s flac after listening to something in flac before.

**Comment by michaelherger** [comment] 2022-06-06 20:24
I've committed a change to 8.3 which should no longer update the `latestFormat`. But I believe I'll have to do some work on the MySB side of things, too. I don't see what exactly is wrong yet.

**Comment by MichaelSch** [comment] 2022-06-06 21:37
I installed the latest nightly. Not sure if you are working in the background but right now the genre channels are broken for me. The player shows the track data (mp3) but does not start the playback.

**Comment by michaelherger** [comment] 2022-06-07 04:35
Working fine here.

But I think your hint about what radios would play losslessly and which ones would not has been very helpful: those genre stations are always requested with an application auth token, rather than the user's. I don't know yet whether this is by design or not. But it's a lead. Thanks!

**Comment by MichaelSch** [comment] 2022-06-07 04:58
Thank you. Now it‘s playing again, don‘t know what the issue was. :)

**Comment by michaelherger** [comment] 2022-06-07 05:11
If you're in EU region, could you please play a new genre station and check the format (after having played some Flac before)?

**Comment by MichaelSch** [comment] 2022-06-07 05:25
Genre stations show flac now as well. Woohoooo!

**Comment by MichaelSch** [comment] 2022-06-07 17:01
Just checked again - for me this issue is solved. I always get flac for everything. Thanks a lot!

**Comment by mherger** [comment] 2022-06-07 20:17
Thanks for the confirmation!

**Closed as completed by mherger** 2022-06-07 20:17 UTC
