### ISSUE TITLE
qobuz plugin sort

### ISSUE THREAD

**Issue by dekoenpi** [LMS-Community/slimserver#860] opened 2023-01-31 12:11 UTC
Hi all,

is it possible to create a qobuz plugin feature request here?
The wish would be the possibility to sort the albums from one artist by year.

Best regards
P-Kay

**Comment by mherger** [comment] 2023-02-01 06:45
This is a dupe of https://github.com/pierrepoulpe/SqueezeboxQobuz/issues/23 - registered in the Qobuz plugin's home.

**Closed as completed by mherger** 2023-02-01 06:45 UTC
