### ISSUE TITLE
Slow loading of playlists

### ISSUE THREAD

**Issue by CDrummond** [LMS-Community/slimserver#905] opened 2023-09-03 06:47 UTC
As reported on the LMS forums:
https://forums.slimdevices.com/forum/user-forums/logitech-media-server/1648066-slow-playlist-loading
https://forums.slimdevices.com/forum/user-forums/3rd-party-software/106269-announce-material-skin?p=1648085#post1648085

Loading of track details from a playlist takes a far greater time than simply loading a playlist into the queue. Prior to 3.4.4, Material skin asks for basically all tracks in a playlist when loading its details in the 'Browse' view. This has been noted to take minutes to load for playlists with 1000s of items, cause high CPU, and even crash LMS. 3.4.4 of Material will load these lists in batches, as per the Default skin. But even changing the Default skin to use a "Items per page" of 500 will cause delays in showing the list.

Now, I accept perhaps loading all details in the playlist is a bit silly (so have changed for 3.4.4). However seeing as Material asks for the complete queue (well actually in batches of 5000) and this is very fast, it seems odd that just asking for playlist details would be so slow.

**Comment by mherger** [comment] 2023-09-04 04:47
Git history tells me I tried to address this 9 years ago - and had to revert my efforts...
<img width="865" alt="Screenshot 2023-09-04 at 06 39 08" src="https://github.com/Logitech/slimserver/assets/1515327/321e4608-4234-4508-b530-06cfa8c2eeca">

This is using pretty old code, which uses an object to relational mapping framework. This later on turned out to be poorly performing in many cases. Most more recent code is using raw SQL for this reason. 

I'll have to create a large playlist to play with this. Looking at the code it's not clear to me where the stalling would happen, as the code sees to yield after each track.

Looking at the output of `--debug database.sql` it seems to run a query for each and every track in the database:

```
SELECT me.id, me.urlmd5, me.url, me.content_type, me.title, me.titlesort, me.titlesearch, me.album, me.primary_artist, me.tracknum, me.timestamp, me.added_time, me.updated_time, me.filesize, me.disc, me.remote, me.audio, me.audio_size, me.audio_offset, me.year, me.secs, me.cover, me.cover_cached, me.vbr_scale, me.bitrate, me.samplerate, me.samplesize, me.channels, me.block_alignment, me.endian, me.bpm, me.tagversion, me.drm, me.musicmagic_mixable, me.dlna_profile, me.musicbrainz_id, me.lossless, me.lyrics, me.replay_gain, me.replay_peak, me.extid, me.virtual, me.coverid FROM tracks me WHERE ( url = ? ): 'spotify:track:5M4NO7Nwgb3FTOr7tl2ONH'
```

**Comment by mherger** [comment] 2023-09-04 05:02
Have you been able to reproduce this issue? I'll have to pick up a Pi or something, because on my 2022 MacBook Pro I can enter a 5k playlist in a fraction of a second...

Oh, that was with local files only. If you decided to read a playlist with that many online tracks, LMS could end up doing thousands of API calls to the online service. I'll have to ask the reporter(s) about what source they're using.

**Comment by CDrummond** [comment] 2023-09-04 07:03
I've created a local only playlist with 1015 tracks. 

To fine the `playlist_id` of this new playlist I used:

```bash
curl 'http://localhost:9000/jsonrpc.js' --data-raw '{"id":10,"method":"slim.request","params":["",["playlists",0,25000,"tags:suxE","menu:1"]]}'
```

Then I used the following to determine how long loading this complete list would take:

```bash
time curl 'http://localhost:9000/jsonrpc.js' --data-raw '{"id":4,"method":"slim.request","params":["",["playlists","tracks",0,25000,"tags:acdeglstAKS","playlist_id:7007"]]}'
```

This produced:
```
real	0m6.118s
user	0m0.006s
sys	0m0.003s
```

So about 6 seconds to load 1015 local-only tracks. This is all running locally on my i5 laptop, with m.2 SSD.

I added the playlist 5 times to the queue, and saved to a new 5075 tracks playlist. The query (on the new playlist ID) now takes about 31 seconds - and used 100% CPU.

**Comment by CDrummond** [comment] 2023-09-04 07:15
For comparison, loading the 5075 playlist into the queue:

```bash
time curl 'http://localhost:9000/jsonrpc.js' --data-raw '{"id":0,"method":"slim.request","params":["01:02:03:04:05:06",["playlistcontrol","cmd:add","playlist_id:7008","library_id:0"]]}'
```
this took:1.2 seconds

Llisting all tracks in queue:
```bash
time curl 'http://localhost:9000/jsonrpc.js' --data-raw '{"id":0,"method":"slim.request","params":["01:02:03:04:05:06",["status",0,25000,"tags:cdegilqtuysAAIKNSxx"]]}'
```
and that took ~0.3 seconds.

So as you can see loading into the queue is **much** quicker.

**Comment by michaelherger** [comment] 2023-09-04 07:20
Yeah, the difference between loading the file into the queue and loading the file to show is very surprising. You'd think they'd have to do the same level of metadata lookup.

I actually re-run the test with local files only. It seems my previous attempt didn't actually read all of the 5k tracks, but somehow stopped midway through when it hit the first non-local track... And with this I can confirm that a 5k local tracks only playlist took about 21s on my dev machine. Now I can investigate. Thanks for insisting 😀.

**Comment by michaelherger** [comment] 2023-09-04 12:24
Here's the result of profiling just the playlist request:

![Screenshot 2023-09-04 at 14 17 58](https://github.com/Logitech/slimserver/assets/2789989/d492cc8f-9443-42fa-aa01-f5abfe39e87e)

Almost all time is spent in `DBIx`, that ORM. There's definitely room for improvement. 

![Screenshot 2023-09-04 at 14 19 03](https://github.com/Logitech/slimserver/assets/2789989/dafbe509-3cdf-4525-be81-b8089df789fc)

I had tried to fix this nine years ago (see 53ceb263d) but decided to revert the change a few weeks later, as it was causing issues with remote tracks. Maybe I should review why exactly I thought it wasn't possible using the more efficient code. After all the status query can handle it.

**Comment by michaelherger** [comment] 2023-09-04 15:34
Still investigating. But while the ORM definitely is super elegant, it's highly inefficient in this particular case. Replacing the hand full of nice lines with about two dozen "optimised" lines brought down execution time by about 75% so far. That's just replacing the `contributorsOfType()` call shown in the above chart. Hopefully there's more to come.

**Comment by michaelherger** [comment] 2023-09-04 16:31
@CDrummond - do you need the genre when listing playlists? This one is a bit more complicated, as it's already broken now: if there's a track with multiple genres, a random one would be picked. If I re-implemented the genre lookup, it would not be guaranteed to return the same random genre as before... 

By removing the genre (and using my latest code which I haven't committed yet), the query would be down from 21s to less than one second 😁. With the genre it's <2.5s.

**Comment by CDrummond** [comment] 2023-09-04 17:19
@michaelherger nope don't need genre. If it's in material's tags param I'll remove.

**Comment by michaelherger** [comment] 2023-09-04 17:56
Yeah, it is. It's the `g` tag. But I actually was using your above curl commands to test. I'll double check the params you're using.

**Comment by CDrummond** [comment] 2023-09-04 18:08
Then it's in the command material is using - I used the browser Dev tools to copy the commands.

Thinking about it now, genre is used to know whether to show composer, conductor, etc. If I don't ask for genre then I can't do that. Not a big deal either way - not using, or getting random genre if multiple

**Comment by michaelherger** [comment] 2023-09-04 18:10
I've got a tweak for it, too. No worries. Also: there's two `l`s in there. And LMS is stupid enough to process it twice. Fixing that (in LMS) shaves off many more CPU cycles.

**Comment by michaelherger** [comment] 2023-09-04 18:15
Please give 8.4 (and your old, greedy playlist browsing code) another try.

**Closed as completed** 2023-09-04 18:15 UTC

**Comment by CDrummond** [comment] 2023-09-08 12:52
@michaelherger Where is the double 'l' ? I can't see that in the code or the examples above.

**Comment by michaelherger** [comment] 2023-09-08 13:01
In the browser's dev tools I'm seeing this as the request sent to the server:

```
{
    "id": 2,
    "method": "slim.request",
    "params": [
        "",
        [
            "playlists",
            "tracks",
            0,
            50,
            "tags:acdeglstAKSlorIT",
            "playlist_id:3472"
        ]
    ]
}
```

There's one between `g` and `s`, and another one between uppercase `S` and `o`: `acdeg_l_stAKS_l_orIT`.

8.4 would not evaluate it twice. But before that it took quite a few unnecessary CPU cycles on those large lists.

**Comment by CDrummond** [comment] 2023-09-08 13:03
Ah! Thanks, spotted now. Its added when Material wants to show tech info. Will fix.

[Edit] I think the issue is when using a sans-serif font lowercase 'l' (ell) and uppercase 'I' (eye) look the same!

**Comment by CDrummond** [comment] 2023-09-09 06:26
Whilst massively quicker than before, its still slower than the queue. A 2500 track playlist served from my Pi4 4GB (on SSD) takes ~12 seconds to load all tracks.

To be honest, I think batching is required here and I don't think playlists of this size are actually a normal use case anyway, so not really worth spending too much time on. Just odd that the queue is so fast.

**Comment by michaelherger** [comment] 2023-09-09 12:27
Nine years ago I tried to rewrite the playlist tracks query to use the same code as the queue (status query). I had to revert it for some reason. But it's true that they shouldn't be any different. After all it's looking up basically the same track information for a bunch of tracks... The status query at some point was re-written to use native SQL without the ORM overhead, of which there still is a lot in the tracks query. But I guess as there was no complaint for about 9 years I didn't spend too much time worrying. We should probably go back to not worry 😀.

**Comment by CDrummond** [comment] 2023-09-09 12:30
I agree, life's too short to worry about extreme edge cases! :)

**Comment by michaelherger** [comment] 2023-09-12 04:45
Sometimes I just can't let go... I looked into the differences between how we create the playlist info in the `status` query vs. `playlists tracks`. I think the big difference still lies in the ORM creation, but not where I thought it was: would loading the large playlist into the queue take a considerable amount of time? I believe that the `status` query doesn't need to create the track objects any more, as they're created when the list is loaded, then kept in memory (the reason why LMS did limit queues to 500 items a few years ago). And that initialization of all the track objects is what takes a lot of time in the `playlists tracks` query. I'm pretty sure we could still shave off a few percents here or there. But IIRC that's where it spends most of the time in the current state.
