### ISSUE TITLE
Podcast plugin: Problem adding podcast "Redirection limit exceeded"

### ISSUE THREAD

**Issue by flurischt** [LMS-Community/slimserver#121] opened 2016-11-23 15:13 UTC
Hi 

I'm trying to add this podcast to LMS: https://talkpython.fm/episodes/rss 
(Note the httpS, the page redirects to https)

Adding this url under settings and clicking "Apply" will run forever. The Server Log contains:
```
[16-11-23 16:12:31.9724] Slim::Formats::XML::gotErrorViaHTTP (310) Error: getting https://talkpython.fm/episodes/rss
Redirection limit exceeded
[16-11-23 16:12:31.9751] Slim::Plugin::Podcast::Settings::__ANON__ (119) Error validating feed https://talkpython.fm/episodes/rss: Redirection limit exceeded
[16-11-23 16:12:31.9786] Slim::Networking::IO::Select::__ANON__ (131) Error: Select task failed calling Slim::Networking::Async::_async_read: Undefined subroutine &Slim::Plugin::Podcast::Settings::string called at /media/disk/slimserver/Slim/Plugin/Podcast/Settings.pm line 121.
; fh=Slim::Networking::Async::Socket::HTTP=GLOB(0x4b2c8e0)
```
and it continues trying...

I'm running the latest public/7.9 branch (commit ff23c8d3a9e0b203aff69a49f094c91ef4ad4ec4 as of now)

**Comment by mherger** [comment] 2016-11-23 16:53
Ahm... how can flag this as a dupe of issue #114 ?

**Closed as completed** 2016-11-23 16:53 UTC
Labels: duplicate

**Comment by flurischt** [comment] 2016-11-23 17:18
Oh sorry, didn't see the otther issue. This one is related to adding the podcast whereas #114 is related to streaming an episode though. But I guess it's the same problem underneath.

**Comment by mherger** [comment] 2016-11-24 12:33
@flurischt - what platform are you running your LMS on? Would you see a warning in server.log complaining about the lack of SSL support (right after the startup)?

I can add this podcast, no problem there.

**Comment by mherger** [comment] 2016-11-24 12:40
Oh, btw: you hit an error in the error handler... Therefore the page didn't return. Should be fixed in git. Thanks!

(this has nothing to do with the failure to handle https URLs, but that failure exposed another issue)

**Comment by flurischt** [comment] 2016-11-24 13:37
I run it on a raspberry pi. Here's the log when I startup:
```
[16-11-24 14:34:48.3438] main::init (384) Starting Logitech Media Server (v7.9.0, git-ff23c8d, 2016-11-22 21:40:12 +0100) perl 5.014002 - arm-linux-gnueabihf-thread-multi-64int
[16-11-24 14:34:49.5780] Slim::Utils::SQLiteHelper::postConnect (374) Optimizing DB because of missing or empty sqlite_stat1 table
[16-11-24 14:34:49.6117] Slim::Schema::forceCommit (2149) Warning: Trying to commit transactions before DB is initialized!
[16-11-24 14:34:52.5792] main::checkDataSource (1107) Warning: Schema updated or no media found in the database, initiating scan.
[16-11-24 14:35:00.2624] Slim::Utils::SQLiteHelper::postConnect (374) Optimizing DB because of missing or empty sqlite_stat1 table
[16-11-24 14:35:00.2814] Slim::Schema::forceCommit (2149) Warning: Trying to commit transactions before DB is initialized!
```

**Comment by flurischt** [comment] 2016-11-24 13:51
Sorry, my bad. IO::Socket::SSL was missing. Adding the podcast now works. But when streaming I can confirm that I have the same problem as in #114

**Comment by stefan-hoehn** [comment] 2016-12-19 20:58
In referring to #114 I upgraded to 7.9. Now I "Can't connect to https: URL lack of IO:Socket:SSL: https://feeds....

Any idea what needs to be done to fix this?

**Comment by mherger** [comment] 2016-12-19 21:36
@stefan-hoehn - you'll need to install IO::Socket::SSL. You better ask around the QNAP forums about how to do this.
