### ISSUE TITLE
Outdated bundled CPAN modules

### ISSUE THREAD

**Issue by mavit** [LMS-Community/slimserver#595] opened 2021-04-27 11:13 UTC
I recently [tripped over](https://github.com/expectingtofly/LMS_BBC_Sounds_Plugin/pull/83#pullrequestreview-644956682) a bug in our bundled version of XML::Simple, 2.15, which I see was fixed upstream in 2012.

This doesn't feel like a great situation to be in.  Is there any appetite for updating this or other bundled modules?

I see from #138 that NixOS is using upstream rather than bundled versions of most modules, so perhaps this would be easier than it might seem.

**Comment by michaelherger** [comment] 2021-04-29 05:44
As discussed in the forums I'd be happy to live in a perfect world where things would just work for everybody. Alas, it's not that easy: for some systems we're stuck with what we have (Windows), therefore must remain compatible. That said, I would welcome an effort trying to create eg. Linux packages which would work with the system's libraries rather than ours.

**Comment by mherger** [comment] 2022-02-01 06:31
Dupe of #138

**Closed as completed by mherger** 2022-02-01 06:31 UTC
