### ISSUE TITLE
Using comment field as disc title for multi-disc albums duplicates disc title

### ISSUE THREAD

**Issue by noneilno** [LMS-Community/slimserver#781] opened 2022-04-09 20:42 UTC
LMS returns "comment / comment" as seen in the following images.

LMS setting:
![img-1](https://user-images.githubusercontent.com/103335931/162590900-ec7e0d6f-09fc-4865-9e45-ea2a15b68052.png)

Appending to queue:
![img-2-2](https://user-images.githubusercontent.com/103335931/162590910-69757d72-eae2-4052-9abf-fcbd98863e84.png)

Database view of the disc 1 data:
![img-2](https://user-images.githubusercontent.com/103335931/162590905-6ac0e2c4-8988-4c3e-947a-b792a1e56c1f.png)

---

LMS Version: 8.2.0 - 1627922070 @ Tue Aug 3 11:43:18 CEST 2021
Database Version: DBD::SQLite 1.58 (sqlite 3.22.0)
piCorePlayer v8.0.0
www v00017
linux 5.10.42-pcpCore-v8 (64)
piCore v13.0
Squeezelite v1.9.9-1392-pCP

Raspberry Pi 4B
PCB Revison: 1.1
Memory: 4096

**Comment by mherger** [comment] 2022-04-10 05:03
Duplicate of #535

**Closed as completed by mherger** 2022-04-10 05:03 UTC
