### ISSUE TITLE
LMS 9: New Sort Order in "New Music" section

### ISSUE THREAD

**Issue by microrache** [LMS-Community/slimserver#1142] opened 2024-08-04 12:01 UTC
I just moved from LMS 8.5 to LMS 9 and have some questions/issues regarding the new sort behaviour for the "New Music" section. The changelog says:

> Add new "Recently Changed" browse mode to complement the "New Music" menu. The latter is no longer based on the file's timestamp, but on the time added to the collection, as stored in the persistant track table.

Where can I set this "recently changed" mode? And is there a doc I am missing explaining the sort modes in more detail?

Let me explain my struggles:

Changing the default sort order to "added" is not ideal for me, as it leads to albums stored further back in the file system show up on top of the "New music" section (in my case albums from artists beginning with "Z"). At first I tried to help myself by shutting down LMS, opening the SQLite database manually, doing an
```
UPDATE tracks SET added_time = "timestamp", updated_time = "timestamp"
```
and starting the server again with that modified `library.db` file, but this had no effect on the display-order in the "New music" menu. Also, I am aware that this is not a good solution, because this update would be necessary after every "Delete database and do a complete rescan" - which is quite unpleasant.

So, my questions are:
1. Are the sort modes configurable as the Changelog suggests? If yes, where is this setting?
2. Just out of curiosity: Can you explain why my SQL update is not working? When I do 
```
SELECT a.* 
FROM tracks AS t
LEFT JOIN albums AS a
       ON a.id = t.album
GROUP BY a.id
ORDER BY t.added_time DESC
LIMIT 100
```
I get my desired new-album-list in the file-attribute-order, but LMS (which probably uses not this, but to my understanding a somehow similar SQL statement under the hood) still shows the albums in the original added-order with the Z-artist's albums being on top. Is there some cache-file I have to delete after manually editing the database? Are there some other timestamps in the database I would have to update to achieve the desired display-order being the file's MTIME attributes?

Thank you for helping and thank you so much for maintaining LMS in general.

**Comment by michaelherger** [comment] 2024-08-04 18:43
Please see Settings/Player/[your player]/Extended Browse Modes.

**Comment by pbrekelmans** [comment] 2024-10-01 17:22
I noticed a maybe related behavior. I routinely update my LMS installation to the latest release available
Since a few weeks all my spotty albums get listed on top of the 'New Music' section, regardless of their 'date added'. This was never the case before. Newly added local files, after this change of behavior, still appear on top though..

I am currently running:
Version: 9.0.0 - 1727189518 @ Wed Sep 25 02:56:59 UTC 2024
Operating system: Debian (Docker) - EN - utf8
Platform Architecture: x86_64-linux
Perl Version: 5.36.0 - x86_64-linux-gnu-thread-multi
Audio::Scan: 1.06
IO::Socket::SSL: 2.081
Database Version: DBD::SQLite 1.58 (sqlite 3.22.0)

**Comment by michaelherger** [comment] 2024-10-13 06:18
I can't confirm this. I have some Spotify, then a local album, then some more online albums etc. mixed. Are you sure it's all Spotify first?

**Comment by michaelherger** [comment] 2024-10-18 12:39
Could you please update to the latest image, then run a wipe & rescan and check again? I think I've been able to reproduce what you saw and committed a change to improve the behaviour: see https://github.com/LMS-Community/slimserver/commit/691aa9ca054130cb7de2712285626e9a38ef78c6.

**Comment by pbrekelmans** [comment] 2024-10-25 13:20
Yes! I updated to Version: 9.0.0 - 1729437396 @ Mon Oct 21 02:58:30 UTC 2024 and did a wipe and rescan.
Now it looks good, consistent with dates added for local files and spotify alike, you fixed it, great!

**Closed as completed** 2024-10-25 13:35 UTC
