### ISSUE TITLE
Rescan buttons "Classic" skin

### ISSUE THREAD

**Issue by kidstypike** [LMS-Community/slimserver#410] opened 2020-08-31 08:56 UTC
Rescan buttons alongside individual media folders in Classic skin do nothing, which affects the "Material" skin.

**Comment by michaelherger** [comment] 2020-08-31 15:29
Working fine here - with one important limitation: once you've clicked one of those buttons you'd have to refresh the page once the scan has finished, as the buttons will be disabled while a scan is running. Can you double-check this behaviour?

**Comment by kidstypike** [comment] 2020-08-31 15:51
Just tried again using the Classic skin (not Default), button does nothing, no scan initiated.
![rescanClassic](https://user-images.githubusercontent.com/70511925/91739577-09d2d080-ebaa-11ea-801e-1cead4eb4ae9.jpg)

**Comment by kidstypike** [comment] 2020-08-31 15:52
Sorry, didn't mean to close the issue.

**Comment by michaelherger** [comment] 2020-09-01 19:59
I tested this again, and both Classic as well as Material do trigger a scan when I hit one of those buttons. What might be confusing, and I mentioned this before, is that once you've clicked one of those buttons, the other buttons would indeed become inactive, without showing any sign of this limitation. You'd have, after the scan has finished, reload the page to get the buttons back.

In the Default skin there's a poll going on in the back ground which would re-enable the buttons once the scan is done. I might want to re-create this for the old skins.

**Comment by kidstypike** [comment] 2020-09-01 20:21
Michael, with respect, If I add an album to say the first media folder in the list (/mnt/musicbox5/Squeezebox music) and click the rescan button alongside, nothing happens, no scan is initiated, I'm not attempting to click any of the other rescan buttons.

Works fine in Default skin.

Don't know what else to say.

**Comment by mherger** [comment] 2020-09-02 04:45
Please enable info logging for `control.command`, try again, share your log files (both server and scanner).

**Comment by kidstypike** [comment] 2020-09-02 07:11
Logs attached,

[server.log.zip](https://github.com/Logitech/slimserver/files/5160632/server.log.zip)
[scanner.log.zip](https://github.com/Logitech/slimserver/files/5160634/scanner.log.zip)

**Comment by mherger** [comment] 2020-09-10 10:34
I do indeed not see a correlation between the scanner.log's time stamps and traces in server.log. What browser are you using?

**Comment by kidstypike** [comment] 2020-09-10 10:43
Well exactly, the scanner log is from a previous scan initiated by me from the "default" skin a couple of days earlier. As I said the scan buttons in the classic skin do nothing, so nothing in the scanner log.

**Comment by kidstypike** [comment] 2020-09-10 10:53
Just tried this using:

Google Chrome
Firefox
Brave
Opera
Microsoft Edge

none work using classic skin.

**Comment by mherger** [comment] 2020-09-11 10:09
Could you please share a screenshot of your basic settings? Or the server.prefs file?

**Comment by kidstypike** [comment] 2020-09-11 10:37
![Basic settings](https://user-images.githubusercontent.com/70511925/92913692-e702b080-f422-11ea-8a32-692e1e58de88.jpg)

[server.zip](https://github.com/Logitech/slimserver/files/5208385/server.zip)

**Comment by michaelherger** [comment] 2020-09-11 12:05
Trying to reproduce your issue brought up other bugs, but I still have no clue why that would not work. And you seem to be the only one suffering from this... would you have another machine where you could run a test whether this was a problem with that installation?

**Comment by kidstypike** [comment] 2020-09-11 19:58
Perhaps there's not many regulars use more than one media folder **and** try to scan just one of them using the Material or Classic skin?

Anyway, I've just tried this with exactly the same five media folders (on a different drive) on Win10 64 Pro/LMS 7.9.3 August 23rd. With the same result, clicking one of the "Rescan" buttons using the Classic skin does nothing except flash the screen for a millisecond, but works fine using the Default skin.

**Comment by mherger** [comment] 2021-02-23 16:12
I looked into this code again. Unfortunately there's no useful logging there. Would you be able to edit a file or two to add some log statements?

**Comment by kidstypike** [comment] 2021-02-23 16:50
I'll give it a go, don't expect great things though.

**Comment by michaelherger** [comment] 2021-02-25 05:54
Ok, could you please add the following two `warn` statements, then restart LMS and click one of those rescan buttons. What do you get in `server.log`?

```diff
diff --git a/Slim/Web/Settings/Server/Basic.pm b/Slim/Web/Settings/Server/Basic.pm
index f07f6bc74..d76cb15c5 100644
--- a/Slim/Web/Settings/Server/Basic.pm
+++ b/Slim/Web/Settings/Server/Basic.pm
@@ -89,6 +89,7 @@ sub handler {
 		my $singleDirScan;
 		for (my $i = 0; defined $paramRef->{"pref_mediadirs$i"}; $i++) {
 			if (my $path = $paramRef->{"pref_mediadirs$i"}) {
+				warn Data::Dump::dump($oldPaths{$path}, $path);
 				delete $oldPaths{$path};
 				push @paths, $path;
 
@@ -108,6 +109,7 @@ sub handler {
 
 		my $oldCount = scalar @{ $prefs->get('mediadirs') || [] };
 
+		warn Data::Dump::dump(\%oldPaths, \@paths, $singleDirScan);
 		if ( keys %oldPaths || !$oldCount || scalar @paths != $oldCount ) {
 			$prefs->set('mediadirs', \@paths);
 		}

```

**Comment by kidstypike** [comment] 2021-02-25 08:04
As I don't have a clue where or how to add this, I think it's best if we stop right here.

Thanks.

**Comment by michaelherger** [comment] 2021-02-25 13:54
Interesting finding found by garym:

> I get the exact same results as you (LMS 8.1.2 running on rPi4B 7.01). First "rescan" button does nothing (and reports no error or anything, just nothing happens). the 2nd one does rescan as expected.

Still can't reproduce it, though...

**Comment by kidstypike** [comment] 2021-02-25 16:42
I'm sorry I cannot assist further here.

**Comment by mherger** [comment] 2022-07-25 14:32
@Apesbrain - please try what I outlined in https://github.com/Logitech/slimserver/issues/410#issuecomment-785633369

As you're on Windows this might actually be impossible 😞. Would you mind sharing your server.log file with me?

**Comment by Apesbrain** [comment] 2022-07-25 14:49
> Would you mind sharing your server.log file with me?

No problem, but when I click on the suspect button there is nothing generated in the log.  Can you tell me which logging parameters to enable?

I see the instruction above regarding "warn" statements, but do not know how to add this code.

**Comment by michaelherger** [comment] 2022-07-25 15:02
I'm sorry, I wanted to ask about server.prefs, rather than server.log...

**Comment by Apesbrain** [comment] 2022-07-25 16:45
Ok, will send to you via Forum.  Thanks.

**Comment by michaelherger** [comment] 2022-07-26 05:03
Thanks. Nothing obviously wrong in that file (except for an insane number of player configurations 😁).

Are you familiar with the browsers' dev tools? Could you please, right after loading the basic settings page, right click the button to see whether it's flagged `disabled`? Can you even click that button? If so: can you check the "Network" or similar tab in the dev tools to see what parameters are being sent to the server when you hit that button?

**Comment by Apesbrain** [comment] 2022-07-26 11:13
Hope these attachments are helpful.

![Clipboard01](https://user-images.githubusercontent.com/26585705/180992816-7a61b13e-9682-4670-b323-8a6b15853d8e.jpg)
![Clipboard02](https://user-images.githubusercontent.com/26585705/180992820-74dc5aee-3cdc-406f-8ab5-e44af84a676d.jpg)

**Comment by michaelherger** [comment] 2022-07-26 13:01
Unfortunately in the second screenshot the important part is hidden behind the console tab. Please close it (cross on the right), and make sure you highlight the request to `basic.html` which sent a `POST` request:

![POSTrequest](https://user-images.githubusercontent.com/2789989/181011521-961263e1-6399-4f63-b2c3-006ed6f5a0da.png)

Then change to the `Headers` tab:
![headers](https://user-images.githubusercontent.com/2789989/181012121-d2a2b491-9e8d-4ad6-a644-74ff0a81b74a.png)

**Comment by Apesbrain** [comment] 2022-07-26 13:31
Hope this is it:

![Clipboard01](https://user-images.githubusercontent.com/26585705/181018210-f2a5de85-28b3-4e0f-b6b8-4258945d86a5.jpg)

**Comment by michaelherger** [comment] 2022-07-26 14:54
Ok, I added some logging to this handler. Please get the next build (due out in a bit), then enable INFO logging for `scan.scanner`. Hit the button and look for `Path information for single dir scan` in `server.log`.

**Comment by Apesbrain** [comment] 2022-07-26 16:19
Just installed build 8.3.0 - 1658847186 @ Tue Jul 26 17:16:50 WEDT 2022 and followed your instructions.  No such line appears in server.log.  Wrong build?

**Comment by michaelherger** [comment] 2022-07-26 21:18
I'm missing the `saveSettings` parameter in your last screenshot. Is it really not there, or is it hidden at the bottom of the params list?

**Comment by Apesbrain** [comment] 2022-07-26 23:09
It's not there.

**Comment by michaelherger** [comment] 2022-07-27 04:52
Ok, that would explain why the scan isn't triggered. Now the question is: why is it not there... I've double checked with Safari, Chrome and Firefox, and it's working with all of them here. 

Are you using any add-ons in your browsers which might have an impact on the javascript or form submission behavior? Any non-standard setting you're using?

Looking at the page's code I see that we added some "hack" for Safari specifically to work around an issue which sounds similar for Safari only - 14 years ago! The message reads (with all my typos 😬):

> add hidden "saveSettins" form element for Safari, as it doesn't send the submit button's value when submitted using JS.

I wonder whether that's a behavior Safari introduced a long time ago, and others are following _optionally_. I might just enable that hack for all browsers.

**Comment by michaelherger** [comment] 2022-07-27 05:02
Now I feel really stupid... as I fired up all browsers again to check whether they would still work with the above suggested change I'm suddenly seeing the reported behavior... I must have tested this a dozen times, even only just installed Firefox to run this test - and did not see the problem before (see my screenshots from Chrome, where `saveSettings` is prominently at the top). Oh well... the workaround does its job for all of them. Triple checked going back and forth between modified and original code.

**Closed as completed** 2022-07-27 05:07 UTC
Labels: can't reproduce

**Comment by kidstypike** [comment] 2022-07-27 07:41
Thanks, working in Material now.

**Comment by Apesbrain** [comment] 2022-07-27 10:54
Thanks for persevering on this one!

**Comment by mherger** [comment] 2022-10-11 09:29
> Thanks, working in Material now.

Good to know! I totally forgot to test Material, too!
